config/routes.rb
Rails.application.routes.draw do
  resources :oauth do
    collection do
      get 'twitcas_auth'
      get 'twitcas_callback'
    end
  end

  resources :streaming do
    collection do
      get 'play'
      post 'hook'
    end
  end

  root to: "top#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/live_stream.rb
# == Schema Information
#
# Table name: live_streams
#
#  id              :integer          not null, primary key
#  twitcas_user_id :integer          not null
#  movieid         :string(255)
#  live_url        :string(255)
#  live_title      :string(255)
#  thumbnail_url   :string(255)
#  started_at      :datetime
#  finished_at     :datetime
#  state           :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_live_streams_on_movieid          (movieid)
#  index_live_streams_on_twitcas_user_id  (twitcas_user_id)
#  moi_voice_live_finished_at_index       (started_at,finished_at)
#

class LiveStream < ApplicationRecord
  belongs_to :user, class_name: 'TwitcasUser', foreign_key: :twitcas_user_id

  enum state: [:stay, :standby, :playing, :finish]
  has_many :comments, class_name: 'LiveStreamComment', foreign_key: :live_stream_id
end

app/models/live_stream_comment.rb
# == Schema Information
#
# Table name: live_stream_comments
#
#  id                 :integer          not null, primary key
#  twitcast_user_id   :string(255)      not null
#  twitcast_social_id :string(255)
#  live_stream_id     :integer          not null
#  duration           :integer          default("0"), not null
#  message            :text(65535)
#  twitter_status_id  :string(255)
#  voice_path         :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_live_stream_comments_on_duration           (duration)
#  index_live_stream_comments_on_live_stream_id     (live_stream_id)
#  index_live_stream_comments_on_twitcast_user_id   (twitcast_user_id)
#  index_live_stream_comments_on_twitter_status_id  (twitter_status_id)
#

class LiveStreamComment < ApplicationRecord
end

app/models/twitcas_user.rb
# == Schema Information
#
# Table name: twitcas_users
#
#  id                      :integer          not null, primary key
#  twitcas_user_id         :string(255)      not null
#  twitcast_uesr_screen_id :string(255)      not null
#  name                    :string(255)
#  profileimage_url        :string(255)
#  access_token            :text(65535)
#  expires_in              :integer          default("0"), not null
#  last_logined_at         :datetime         not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_twitcas_users_on_twitcas_user_id          (twitcas_user_id) UNIQUE
#  index_twitcas_users_on_twitcast_uesr_screen_id  (twitcast_uesr_screen_id)
#

class TwitcasUser < ApplicationRecord
  has_many :live_straems, class_name: 'LiveStream', foreign_key: :twitcas_user_id

  TWITCAS_API_URL_ROOT = "https://apiv2.twitcasting.tv"

  def self.get_oauth_url
    apiconfig = YAML.load(File.open(Rails.root.to_s + "/config/apiconfig.yml"))
    return TWITCAS_API_URL_ROOT + "/oauth2/authorize?client_id=" + apiconfig["twitcas"]["client_id"] + "&response_type=code"
  end

  def self.oauth!(code, redirect_url)
    apiconfig = YAML.load(File.open(Rails.root.to_s + "/config/apiconfig.yml"))
    http_client = HTTPClient.new
    request_params = apiconfig["twitcas"].merge({
      code: code,
      grant_type: "authorization_code",
      redirect_uri: redirect_url
    })
    url = TWITCAS_API_URL_ROOT + "/oauth2/access_token"

    response_oauth = http_client.post(url, request_params)
    hash = JSON.parse(response_oauth.body)
    request_user_header = {
      'Content-Type' => 'application/json;charset=UTF-8',
      'Authorization' => 'Bearer ' + hash["access_token"]
    }
    response_user = http_client.get(TWITCAS_API_URL_ROOT + "/verify_credentials", {}, request_user_header)
    user_hash = JSON.parse(response_user.body)
    user = TwitcasUser.find_or_initialize_by(twitcas_user_id: user_hash["user"]["id"])
    user.update!(twitcast_uesr_screen_id: user_hash["user"]["screen_id"], access_token: user_hash["access_token"], name: user_hash["user"]["name"], last_logined_at: Time.now, expires_in: hash["expires_in"])
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :permit_all_params

  def permit_all_params
    params.permit!
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def twitcas_auth
    redirect_to(MoiVoice::TwitcasUser.get_oauth_url)
  end

  def twitcas_callback
    user = MoiVoice::TwitcasUser.oauth!(params[:code], twitcas_callback_moi_voice_oauth_url)
    redirect_to(play_moi_voice_streaming_path(user_id: user.id))
  end
end

app/controllers/streaming_controller.rb
class StreamingController < BaseController
  protect_from_forgery

  def play
    @twitcas_user = TwitcasUser.find_by(id: params[:user_id])
    #@live_straem = load_or_create
  end

  def hook
    payload = JSON.parse(params[:payload])
    @twitcas_user = TwitcasUser.find_by(twitcast_uesr_screen_id: payload["userid"])
    live_straem = load_or_create
    if payload["action"] == "live_start"
      live_straem.update!(state: LiveStream.states[:playing], started_at: Time.now)
    elsif payload["action"] == "live_end"
      live_straem.update!(state: LiveStream.states[:finish], started_at: Time.now)
    end
    head(:ok)
  end

  private
  def load_or_create
    live_straem = @twitcas_user.live_straems.find_by(state: [LiveStream.states[:stay], LiveStream.states[:playing]])
    if live_straem.blank?
      live_straem = @twitcas_user.live_straems.create(state: LiveStream.states[:stay])
    end
    return live_straem
  end
end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoiVoice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/streaming/play.html.erb
<script>
  var url = window.location.href
  var host = window.document.location.host;

  var synthes = new SpeechSynthesisUtterance(
    '日本語のテキストを認識させるには、lang 属性に ja-JP を指定します。'
  );
  synthes.lang = "ja-JP"
  // 音声再生
  speechSynthesis.speak(synthes);

  var ws;
  if(url.startsWith("https://")){
    ws = new WebSocket('wss://' + host + "/cable");
  }else{
   ws = new WebSocket('ws://' + host + "/cable");
  }
  var create_room = function(){
    var command = {command: "subscribe"}
    var channel_params = {channel: "StreamingChannel", stream_id: <%= 1 %>}
    command["identifier"] = JSON.stringify(channel_params);
    ws.send(JSON.stringify(command));
  }
  ws.onopen = function(event){
    create_room();
  };
  ws.onmessage = function (event) {
    console.log(event);
    //$("#list").append($('<li>').text(event.data));
  };
</script>
    
<div class="contener">
  <h2>配信中</h2>
  <ul id="list"></ul>
  <ul class="btn_s">
    <li><%= link_to("エンド", root_path) %></li>
  </ul>
</div>

app/views/top/index.html.erb
<div class="contener">
  <%= image_tag("logo_ogp_blue", class: "logo") %>
  <h2>モイ！ボイス</h2>
  <ul class="btn_s">
    <li><%= link_to("スタート", twitcas_auth_oauth_index_path) %></li>
  </ul>
</div>

app/views/top/page.html.erb
<div class="contener">
  <%= image_tag("logo_ogp_blue", class: "logo") %>
  <h2>モイ！ボイス</h2>
  <ul class="btn_s">
    <li><%= link_to("スタート", twitcas_auth_moi_voice_oauth_path) %></li>
  </ul>
</div>